from utils import load_monk_data, get_encoder
import torch
# ... importi torch e definisci la classe MLP ...

# Usi la STESSA funzione di caricamento
X_train_raw, y_train = load_monk_data('monks-1.train')
# ... stesso encoding ...
# ... trasformazione in tensor ...
# ... training loop ...
